version: '3.1'

services:
  joomla:
    image: joomla
    restart: always
    links:
      - joomladb:mysql
    ports:
      - 8080:80
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: example

  joomladb:
    image: mysql:5.6
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: joomladb
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
      - joomladb:mysql
    ports:
      - 8000:80
    environment:
      PMA_HOST: joomladb

